import jsPDF from 'jspdf';

export function exportGrowthReportPdf(childData, predictedData, bmiData, whoData, aiAdvice) {
  const doc = new jsPDF();

  const childName = childData.name || 'เด็ก';
  const genderTxt = (childData.gender === 'female' || childData.gender === 'girl') ? 'หญิง' : 'ชาย';

  // Title Header
  doc.setFillColor(16, 185, 129); // Emerald color
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('KidGrowth AI - Growth & Height Assessment', 15, 20);

  // Child Profile Section
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.text('1. Profile Information', 15, 42);

  doc.setFontSize(11);
  doc.text(`Name: ${childName}`, 15, 52);
  doc.text(`Gender: Child (${genderTxt})`, 110, 52);
  doc.text(`Age: ${childData.age || '-'} Years`, 15, 60);
  doc.text(`Current Height: ${childData.height || '-'} cm`, 110, 60);
  doc.text(`Current Weight: ${childData.weight || '-'} kg`, 15, 68);

  // Predictions & BMI Section
  doc.setFontSize(14);
  doc.text('2. Growth Predictions & BMI Metrics', 15, 82);

  doc.setFontSize(11);
  if (predictedData) {
    doc.text(`Predicted Adult Target Height: ${predictedData.target} cm (${predictedData.min} - ${predictedData.max} cm)`, 15, 92);
  }
  if (bmiData) {
    doc.text(`BMI: ${bmiData.bmi} (${bmiData.category})`, 15, 100);
  }
  if (whoData) {
    doc.text(`WHO Height Standard (Age ${whoData.matchedAge}): ${whoData.whoAverageHeight} cm -> Status: ${whoData.heightStatus}`, 15, 108);
  }

  // Parents Profile
  doc.setFontSize(14);
  doc.text('3. Parents Profile', 15, 122);
  doc.setFontSize(11);
  doc.text(`Father Height: ${childData.fatherHeight || '-'} cm`, 15, 132);
  doc.text(`Mother Height: ${childData.motherHeight || '-'} cm`, 110, 132);

  // Recommendations Summary
  doc.setFontSize(14);
  doc.text('4. Healthcare & AI Recommendations', 15, 148);
  doc.setFontSize(10);
  
  if (aiAdvice) {
    const splitSummary = doc.splitTextToSize(`Summary: ${aiAdvice.overallSummary}`, 180);
    doc.text(splitSummary, 15, 158);

    doc.text('Recommended Actions:', 15, 175);
    doc.text('- Milk & Calcium: 2-3 cups per day', 20, 183);
    doc.text('- Eggs & Protein: 1-2 eggs per day', 20, 191);
    doc.text('- Exercise: Vertical jumping, basketball, swimming (60 mins/day)', 20, 199);
    doc.text('- Sleep: 9-11 hours per day (Bedtime before 21:30)', 20, 207);
  }

  // Footer
  doc.setFillColor(241, 245, 249);
  doc.rect(0, 275, 210, 22, 'F');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by KidGrowth AI | Smart Child Growth Predictor & BMI Analyzer', 15, 285);
  doc.text(`Date: ${new Date().toLocaleDateString('th-TH')}`, 150, 285);

  doc.save(`KidGrowth_Report_${childName}.pdf`);
}
